name: Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Debug Variables
        run: |
          echo "JENKINS_URL: '$JENKINS_URL'"
          echo "JENKINS_JOB: '$JENKINS_JOB'"
          echo "JENKINS_USER: '$JENKINS_USER'"
          echo "JENKINS_TOKEN: '$JENKINS_TOKEN'"

      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: "https://jenkins.agilecyber.com/"
          JENKINS_JOB: "PETAPP_SANITY"
          JENKINS_USER: "agilecyber"
          JENKINS_TOKEN: "1186ccab74ae46177ea02c605d794768e6"
        run: |
          curl -v -X POST "${JENKINS_URL}/job/${JENKINS_JOB}/build?token=${JENKINS_TOKEN}" \
            --user "${JENKINS_USER}:${JENKINS_TOKEN}"
