name: Build APK

on:
  push:
    branches:
      - master  # Or the specific branch you'd like to trigger the build
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'  # Update to the required Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: " https://8773-2401-4900-1ce3-7655-ddf7-7fb8-d3d3-8b67.ngrok-free.app"
          JENKINS_JOB: "Appium"
          JENKINS_USER: "annsherry"
          JENKINS_TOKEN: "110bee13155090af355e95356b48653df4"
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB/build?token=$JENKINS_TOKEN" \
            --user "$JENKINS_USER:$JENKINS_TOKEN"


   
