name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch

jobs:
  trigger-Jenkins:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Trigger Jenkins Job
    - name: Trigger Jenkins Build
      run: |
        curl -X POST "$JENKINS_URL?token=$JENKINS_TOKEN" \
        --user "$JENKINS_USER" \
        --data-urlencode json='{"parameter": [{"name": "ENVIRONMENT", "value": "staging"}]}'
      env:
        JENKINS_URL: ${{ http://localhost:8080/ }}
        JENKINS_TOKEN: ${{ 11cdf58bf8d7c7ef2f1841bdbfdfabd51b }}
        JENKINS_USER: ${{ annsherry }}
