name: Build APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Debug Variables
        run: |
          echo "JENKINS_URL: '$JENKINS_URL'"
          echo "JENKINS_JOB: '$JENKINS_JOB'"
          echo "JENKINS_USER: '$JENKINS_USER'"
          echo "JENKINS_TOKEN: '$JENKINS_TOKEN'"
          echo "JENKINS_ENV: '$JENKINS_ENV'"

      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: "https://jenkins.agilecyber.com"
          JENKINS_JOB: "PETAPP_SANITY"
          JENKINS_USER: "agilecyber"
          JENKINS_TOKEN: "119b94eea1e127cc9fd3cae9ac2fb094cd"
          JENKINS_ENV: "JENKINS_ENV"
          
        run: |
          CRUMB=$(curl -s -u "${JENKINS_USER}:${JENKINS_TOKEN}" "${JENKINS_URL}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
          curl -v -X POST "${JENKINS_URL}/job/${JENKINS_JOB}/build" \
            -H "$CRUMB" \
            --user "${JENKINS_USER}:${JENKINS_TOKEN}" \
            --data ""
