
name: Build APK
 
on:
  push:
    branches:
      - master  # Or the specific branch you'd like to trigger the build
  workflow_dispatch:
 
jobs:
  build-apk:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # Update to the required Flutter version
 
    - name: Install dependencies
      run: flutter pub get
 
    - name: Build APK (Debug)
      run: flutter build apk --debug
  - name: Trigger Jenkins Build
      run: |
        curl -X POST "http://localhost:8080/job/Appium/build?token=Token" \
          --user "annsherry:110bee13155090af355e95356b48653df4"
 
   
