name: Build and Trigger Jenkins

on:
  push:
    branches:
      - master  # Runs when code is pushed to the master branch
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Debug Variables
        run: |
          echo "JENKINS_URL: 'https://jenkins.agilecyber.com'"
          echo "JENKINS_JOB: 'PETAPP_SANITY'"
          echo "JENKINS_USER: 'agilecyber'"
          echo "JENKINS_TOKEN: '11ea4aef6175bdf2ef5f54d3c612d22065'"
          echo "JENKINS_ENV: 'UAT'"

  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: build-apk  # Ensure APK build completes before triggering Jenkins

    steps:
      - name: Trigger Jenkins Build
        run: |
          echo "Fetching Jenkins Crumb Token..."
          CRUMB=$(curl -s -u "agilecyber:11ea4aef6175bdf2ef5f54d3c612d22065" "https://jenkins.agilecyber.com/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          echo "Triggering Jenkins Job: PETAPP_SANITY"
          curl -v -X POST "https://jenkins.agilecyber.com/job/PETAPP_SANITY/buildWithParameters?ENVIRONMENT=UAT" \
            -H "$CRUMB" \
            --user "agilecyber:11ea4aef6175bdf2ef5f54d3c612d22065" \ 
            --data ""


