name: Build and Trigger Jenkins

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: build-apk

    steps:
      - name: Trigger Jenkins Build
        run: |
          echo "Triggering Jenkins Job: PETAPP_SANITY"

          # Send API request to trigger the Jenkins job
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://jenkins.agilecyber.com/job/PETAPP_SANITY/buildWithParameters?ENVIRONMENT=UAT" \
            --user "agilecyber:11ea4aef6175bdf2ef5f54d3c612d22065" \
            --data "")

          # Check if the job was successfully triggered
          if [ "$RESPONSE" -eq 201 ]; then
            echo "✅ Jenkins Job Triggered Successfully!"
          else
            echo "❌ Failed to Trigger Jenkins Job! HTTP Response: $RESPONSE"
            exit 1
          fi
